
n: 1;
fname: printf(false, "vars.mcf.~d", n);
scale: 4;
min_phys: [0, 0, 0];
max_phys: [8, 8, 16];
num_part_x: round(40/scale);
num_part_y: round(40/scale);
num_part_z: round(80/scale);
cut_off:    0.8*scale;
with_stdout(fname,
  printf(true, "NUM_PART_X=~d~%", num_part_x),
  printf(true, "NUM_PART_Y=~d~%", num_part_y),
  printf(true, "NUM_PART_Z=~d~%", num_part_z),
  printf(true, "cut_off=~g~%", cut_off));
